FROM ubuntu:latest
# used the latest Ubuntu as the base image

RUN apt-get update
# update APT package lits

RUN apt-get upgrade -y
# Upgrade installed packages

CMD ["echo", "Hello, World!"]
# Command to run when the container starts